name: Android CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set gradle.properties from secret
        run: echo "${{ secrets.KEYSTORE_PROPERTIES }}" | base64 --decode > keystore.properties


      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run KtLint
        run: ./gradlew ktlintCheck --info --stacktrace

      - name: Run all build and test tasks
        run: |
          ./gradlew :composeApp:assembleInternalDebug :composeApp:assembleProductionRelease --stacktrace